name: Latest ithome blog update workflow

on:
  schedule: 
    # 自動更新時間
    - cron: "30 18 * * *" 
  workflow_dispatch: # 手動更新

permissions:
  contents: write # 讀寫權限

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ithome Article Post Action
        uses: Charonyuu/ithome_blog_upload@v1
          with:
              ghToken: ${{ secrets.GITHUB_TOKEN }}
              userId: "20162289"
              like: False
              comment: False